/** Agencias autorizadas para ver y usar la búsqueda Vuelo + Hotel */
export const CORREOS_VUELO_HOTEL = [
  "migfratravelcoop@gmail.com",
  "infoasesoras2022@gmail.com",
  "aljornas.travelcoop@gmail.com",
  "aljornastour.reservas@gmail.com",
  "travelred20@gmail.com",
  "alma@pasionxviajes.com",
  "Xpresstours.cucuta@gmail.com",
  "VIAJAPASTO@GMAIL.COM",
  "maryutravel@gmail.com",
  "viajaconsanta@gmail.com",
  "lidergeneral@travelshopco.com",
  "kowawatravel@gmail.com",
  "Operadordeviajesgoglobe@gmail.com",
  "wowtripco@gmail.com",
  "ferney92@hotmail.com",
  "agenciadtravelsas@gmail.com",
  "aventureros360@gmail.com",
  "amarillotours25@gmail.com",
  "viajesluxury@gmail.com",
  "viaggicontact@gmail.com",
  "info@agenciaworldtour.com",
  "reservasviajadeverdadcol@gmail.com",
  "agenciadeviajesmodoavion@gmail.com",
  "marysolviajesyturismo@gmail.com",
  "iinfo.viajes@gmail.com",
  "asistentedegerencia2@orangetravelyturismo.com",
  "Traveltourdelllano23@gmail.com",
  "itertravelagenciadeviajes@gmail.com",
  "marypaseos1@gmail.com",
  "nassautouragency@gmail.com",
  "elianamora.flyandgo@gmail.com",
  "aleidacastrillon-2012@hotmail.com",
  "volemosagenciadeviajes@gmail.com",
  "letripagencia@gmail.com",
  "publisherconlicencia@hotmail.com",
  "ferreiratour2024@gmail.com",
  "fac.turisuripiales@gmail.com",
  "reservas.migfratour@gmail.com",
  "escapateya45@gmail.com",
  "agenciadeviajesamar@gmail.com",
  "administracion@universetravel.com.co",
  "faugariba@gmail.com",
  "turisventurvalle@gmail.com",
  "Viajerossinlimitepop@gmail.com",
  "viajesveranotours@hotmail.com",
  "representacionessolyarena@gmail.com",
  "gerencia@suntravel.com.co",
  "camila.ariza@livetravel.com.co",
  "lacolombianitaagencia@gmail.com",
  "corocoraviajes@gmail.com",
  "innovacion@gehsuites.com",
  "reservas@gehsuites.com"
].map((correo) => correo.toLowerCase());

export const puedeAccederVueloHotel = (email) => {
  const normalizado = (email ?? "").toLowerCase().trim();
  return normalizado !== "" && CORREOS_VUELO_HOTEL.includes(normalizado);
};
